name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

jobs:
  ci:
    name: Test on PHP ${{ matrix.php }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.0', '8.1', '8.2']
      max-parallel: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, pdo_mysql, bcmath
          tools: phpize
          coverage: none
      - name: Setup Packages
        run: |
          composer update -o
      - name: Check Code Style
        run: |
          composer cs-fix
      - name: Run Analyse
        run: |
          composer analyse src
      # - name: Run Test Cases
      #   run: |
      #     composer test